CREATE TABLE `Mmr` (
  `ID` varchar(20) NOT NULL,
  `S_MMR` int DEFAULT NULL,
  `B_MMR` int DEFAULT NULL,
  `T_MMR` int DEFAULT NULL,
  `H_MMR` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `mmr_ibfk_1` FOREIGN KEY (`ID`) REFERENCES `USER` (`USER_ID`) ON DELETE CASCADE
);